dist: trusty
sudo: false
language: node_js
node_js: '9'
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  chrome: stable
install:
  - npm install -g polymer-cli
  - polymer install --variants
before_script:
  - polymer lint --input *.html
script:
  - xvfb-run wct --npm
#  - >-
#    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
#    fi
#env:
#  global:
#    - secure: >-
#
#    - secure: >-
