dist: trusty
sudo: false
language: node_js
node_js:
  - "node"
  - "9.8.0"
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  chrome: stable
install:
  - npm install -g polymer-cli
  - polymer install --variants
before_script:
  - polymer lint --input *.html
script:
  - polymer test

#  - >-
#    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
#    fi
#env:
#  global:
#    - secure: >-
#
#    - secure: >-
