dist: trusty
sudo: false
language: node_js
node_js:
  - "9"
addons:
  firefox: "56"
  chrome: stable
dist: trusty

install:
  - npm install -g polymer-cli
  - npx polymer install --variants
before_script:
  - polymer lint --input *.html
script:
  - npm run test

#  - >-
#    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
#    fi
#env:
#  global:
#    - secure: >-
#
#    - secure: >-
